import path from "node:path";
import fs from "node:fs";
import * as tvmjs from "../../src/index.ts";

const wasmPath = tvmjs.wasmPath();
const wasmSource = fs.readFileSync(path.join(wasmPath, "tvmjs_runtime.wasm"));
// Here we pass the javascript module generated by emscripten as the
// LibraryProvider to provide WASI related libraries.
// the async version of the API.
tvmjs.instantiate(wasmSource, tvmjs.createPolyfillWASI()).then((tvm) => {
  tvm.beginScope();
  const log_info = tvm.getGlobalFunc("testing.log_info_str");
  log_info("hello world");
  // List all the global functions from the runtime.
  console.log("Runtime functions using EmccWASI\n", tvm.listGlobalFuncNames());
  tvm.endScope();
});
